export class StravaActivity {
  constructor(
    public resource_state: number,
    public athlete: {
      id: number,
      resource_state: number
    },
    public name: string,
    public distance: number,
    public moving_time: number,
    public elapsed_time: number,
    public total_elevation_gain: number,
    public type: string,
    public sport_type: string,
    public workout_type: string,
    public id: number,
    public start_date: string,
    public start_date_local: string,
    public timezone: string,
    public utc_offset: number,
    public location_city: string,
    public location_state: string,
    public location_country: string,
    public achievement_count: number,
    public kudos_count: number,
    public comment_count: number,
    public athlete_count: number,
    public photo_count: number,
    public map: {
      id: string,
      summary_polyline: string,
      resource_state: number
    },
    public trainer: boolean,
    public commute: boolean,
    public manual: boolean,
    public visibility: string,
    public flagged: boolean,
    public gear_id: string,
    public start_latlng: number[],
    public end_latlng: number[],
    public average_speed: number,
    public max_speed: number,
    public has_heartrate: boolean,
    public heartrate_opt_out: boolean,
    public display_hide_heartrate_option: boolean,
    public upload_id: string,
    public external_id: string,
    public from_accepted_tag: boolean,
    public pr_count: number,
    public total_photo_count: number,
    public has_kudoed: boolean
  ) { }
}
