name: Deploy Front Angular

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  requirements-frontend:
    uses: MISO-4501-2024-G8/sa-pipeline/.github/workflows/deploy_front_angular.yml@feature/UpdatePipelines
    with:
      project-name: 'sa-front-web'
      source_dir: 'dist/sa-front-web/browser'
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
