name: Requirements Front Angular

on:
  pull_request:
    branches:
      - main
      - qa

jobs:
  requirements-frontend:
    uses: MISO-4501-2024-G8/sa-pipeline/.github/workflows/requirement_front_angular.yml@feature/UpdatePipelines
    with:
      project-name: 'sa-front-web'
      project-key: 'sa-front-web'
      language: 'javascript'
      cache-name: 'cache-sa-front-web'
      install-command: 'npm install'
      sonar-project-properties-file: "sonar-project-custom.properties"
    secrets: inherit
